[train]
seed = 123
epochs = 3

[validate]
fraction = 0.2

[model]
backbone = "resnet18"
pretrained = true
in_chans = 1
backbone_model = ""
freeze_backbone = false

[data]
image_size = 128
mean = 0.5
std = 0.5
batch_size = 64
num_workers = 0
class_nmax = 10_000

[optimizer]
learning_rate = 1e-4

[scheduler]
learning_rate_min = 1e-5