[train]
seed = 123
epochs = 30

[validate]
fraction = 0.2

[model]
backbone = "resnet18"
pretrained = true
in_chans = 1

[data]
image_size = 128
class_nmax = 500
batch_size = 32
mean = 0.5
std = 0.5
num_workers = 0

[optimizer]
learning_rate = 1e-4

[scheduler]
learning_rate_min = 1e-5

[early_stop]
patience = 3
min_delta = -0.005