[train]
seed = 123
epochs = 1

[validate]
fraction = 0.1

[test]
fraction = 0.2

[model]
backbone = "resnet18"
pretrained = false
in_chans = 1
backbone_model = "python/zooplankton/01_results/flat_20260323_162915"
freeze_backbone = false

[data]
image_size = 128
class_nmax = 10_000
batch_size = 64
num_workers = 0

[optimizer]
learning_rate = 1e-5

[scheduler]
learning_rate_min = 1e-6