[train]
seed = 123
epochs = 3

[validate]
fraction = 0.2

[model]
backbone = "resnet18"
backbone_model = ""
pretrained = false
in_chans = 1
freeze_backbone = false

[data]
fraction = 0.2
batch_size = 64
num_workers = 0

[optimizer]
learning_rate = 1e-4

[scheduler]
learning_rate_min = 1e-5