[train]
seed = 123
epochs = 3

[validate]
fraction = 0.2

[model]
backbone = "resnet18"
backbone_model = "python/emnist/01_results/demo_flat"
pretrained = false
in_chans = 1
freeze_backbone = true

[data]
fraction = 0.05
batch_size = 64
num_workers = 0

[optimizer]
learning_rate = 1e-4

[scheduler]
learning_rate_min = 1e-5

[early_stop]
patience = 10_000_000 # ~Inf epochs
min_delta = 0
min_epochs = 0
